ANIMAL_HUNGER_THRESHOLD = 5
ANIMAL_LIFE_LOST_FROM_ATTACK = 4
ANIMAL_DAILY_REGENERATION = -1

LIVING_BEING_DEATH_THRESHOLD = 0
LIVING_BEING_DEFAULT_HP = 10
LIVING_BEING_DAILY_INC_AGE = 1
LIVING_BEING_MAX_AGE = 20
LIVING_BEING_MIN_AGE = 0

PHYTOPHAGE_RECOVERY_AFTER_EATING = 3

PLANT_LIFE_LOST_FROM_ATTACK = 2
PLANT_DAILY_REGENERATION = 1

ZOOPHAGE_RECOVERY_AFTER_EATING = 5
